#!/bin/bash

alias ..='cd ..'
alias ....='cd ../..'
alias ......='cd ../../..'
alias apt='apt-wrapper'
alias apt-depends='apt-cache-recurse depends'
alias apt-rdepends='apt-cache-recurse rdepends'
alias apt-upgrade='sudo apt update && sudo apt upgrade -y'
alias asciicode='man 7 ascii'
alias caps-to-ctrl='setxkbmap -option ctrl:nocaps'
alias cgrep='grep --color=always'
alias dropbox-conflict='find ~/Dropbox -name "*競合*"'
alias dropbox-resolve='find ~/Dropbox -name "*競合*" -delete'
alias e='spacemacs-client -cn'
alias et='spacemacs-client -ct'
alias evince='background evince'
alias j='jobs'
alias man='man-color'
alias o='xdg-open'
alias reload='exec $SHELL'
alias s='autossh'
alias sudo='sudo-wrapper'
alias swap-reset='sudo swapoff -a && sudo swapon -a'
alias t='tig --all'
alias v='less'
alias wget='wget --show-progress'
alias xev="xev | sed -n 's/^ *\(.*keycode.*\), same_screen.*$/\1/p'"
alias xkb-output='setxkbmap -print'
alias youtube-mp4='youtube-dl -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]"'
alias youtube-webm='youtube-dl -f "(bestvideo+bestaudio)[ext=webm]"'
