#!/bin/bash

_apt-cache-recurse() {
  local cur prev words cword
  _init_completion || return
  COMPREPLY=($(apt-cache --no-generate pkgnames "$cur"))
} && complete -F _apt-cache-recurse apt-cache-recurse
