#!/bin/bash

_apt-cache-recurse() {
  local cur prev words cword
  _init_completion || return
  if [[ ! -f /var/cache/apt/pkgcache.bin ]]; then
    sudo apt-cache gencaches &>/dev/null
  fi
  COMPREPLY=($(apt-cache --no-generate pkgnames "$cur"))
} && complete -F _apt-cache-recurse apt-cache-recurse
