#!/bin/bash

_dropbox() {
  local -a list
  case $3 in
    dropbox|help) list=(autostart exclude filestatus help lansync
                        ls proxy puburl running sharelink start
                        status stop throttle update version);;
    autostart|lansync) list=(y n); compopt -o nosort;;
    exclude) list=(list add remove);;
    add|remove) readarray -t list < <(compgen -d);;
    ls|puburl|sharelink) readarray -t list < <(compgen -f);;
    filestatus) readarray -t list < <(compgen -f)
                list+=(-l --list -a --all);;
    proxy) list=(none auto manual);;
    manual) list=(http socks{4,5});;
    start) list=(-i --install);;
    throttle) list=(unlimited);;
  esac
  readarray -t COMPREPLY < <(IFS=$'\n'; compgen -W "${list[*]}" -- "$2")
} && complete -F _dropbox dropbox
