#!/bin/bash

_sshfs-close() {
  local prog='{if ($3 == "fuse.sshfs") print $2}' list
  [[ $1 == $3 ]] && list=$(awk "$prog" /etc/mtab 2>/dev/null)
  readarray -t COMPREPLY < <(IFS=$'\n'; compgen -W "$list" -- "$2")
} && complete -F _sshfs-close sshfs-close
