#!/bin/bash

_apt-install () {
  local cur prev words cword args
  _init_completion || return
  if [[ $prev == @(-t|--target-release) ]]; then
    args=$(apt-cache policy | grep -o '[an]=[^,]*' | cut -f2- -d= | sort -u)
    COMPREPLY=($(compgen -W "$args" -- "$cur"))
  elif [[ $cur == -* ]]; then
    args=(
      -d --download-only
      -y --assume-yes
      --assume-no
      -u --show-upgraded
      -m --ignore-missing
      -t --target-release
      --download
      --fix-missing
      --ignore-hold
      --upgrade
      --only-upgrade
      --allow-change-held-packages
      --allow-remove-essential
      --allow-downgrades
      --print-uris
      --trivial-only
      --remove
      --arch-only
      --allow-unauthenticated
      --allow-insecure-repositories
      --install-recommends
      --install-suggests
      --no-install-recommends
      --no-install-suggests
      --fix-policy
    )
    args+=(
      --show-progress
      --fix-broken --purge --verbose-versions --auto-remove
      -s --simulate --dry-run
      --download
      --fix-missing
      --fix-policy
      --ignore-hold
      --force-yes
      --trivial-only
      --reinstall --solver
      -t --target-release
    )
    COMPREPLY=($(compgen -W "${args[*]}" -- "$cur"))
  else
    if [[ ! -f /var/cache/apt/pkgcache.bin ]]; then
      sudo apt-cache gencaches &>/dev/null
    fi
    COMPREPLY=($(apt-cache --no-generate pkgnames "$cur"))
    [[ $cur == ?(.)/* ]] && _filedir deb
  fi
} && complete -F _apt-install apt-install
