#!/bin/bash

alias asciicode='man 7 ascii'
alias caps-to-ctrl='setxkbmap -option ctrl:nocaps'
alias CAPSLOCK-toggle='xdotool key Caps_Lock'
alias cd='builtin pushd . >/dev/null; builtin cd'
alias cgrep='grep --color=always'
alias dropbox-conflict='find ~/Dropbox -name "*競合*"'
alias dropbox-resolve='find ~/Dropbox -name "*競合*" -delete'
alias headset-init='amixer -c Headset set PCM,0 100%'
alias j='jobs'
alias o='xdg-open'
alias reload='exec $SHELL'
alias s='autossh'
alias swap-reset='sudo swapoff -a && sudo swapon -a'
alias t='tig --all'
alias v='less'
alias wget='wget --show-progress'
alias xclip='xclip -selection clipboard'
alias xev="xev | sed -n 's/^ *\(.*keycode.*\), same_screen.*$/\1/p'"
alias xkb-output='setxkbmap -print'
alias youtube-mp4='youtube-dl -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]"'
alias youtube-webm='youtube-dl -f "(bestvideo+bestaudio)[ext=webm]"'
